// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game_data.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerLoginReq struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code                 int32    `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	Vip                  int32    `protobuf:"varint,5,opt,name=vip,proto3" json:"vip,omitempty"`
	MaxHWIDUseCount      int32    `protobuf:"varint,6,opt,name=maxHWIDUseCount,proto3" json:"maxHWIDUseCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerLoginReq) Reset()         { *m = ServerLoginReq{} }
func (m *ServerLoginReq) String() string { return proto.CompactTextString(m) }
func (*ServerLoginReq) ProtoMessage()    {}
func (*ServerLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc2b35845d6121f3, []int{0}
}

func (m *ServerLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerLoginReq.Unmarshal(m, b)
}
func (m *ServerLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerLoginReq.Marshal(b, m, deterministic)
}
func (m *ServerLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerLoginReq.Merge(m, src)
}
func (m *ServerLoginReq) XXX_Size() int {
	return xxx_messageInfo_ServerLoginReq.Size(m)
}
func (m *ServerLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_ServerLoginReq proto.InternalMessageInfo

func (m *ServerLoginReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ServerLoginReq) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServerLoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerLoginReq) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ServerLoginReq) GetVip() int32 {
	if m != nil {
		return m.Vip
	}
	return 0
}

func (m *ServerLoginReq) GetMaxHWIDUseCount() int32 {
	if m != nil {
		return m.MaxHWIDUseCount
	}
	return 0
}

type ServerLoginRes struct {
	Result               uint32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerLoginRes) Reset()         { *m = ServerLoginRes{} }
func (m *ServerLoginRes) String() string { return proto.CompactTextString(m) }
func (*ServerLoginRes) ProtoMessage()    {}
func (*ServerLoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc2b35845d6121f3, []int{1}
}

func (m *ServerLoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerLoginRes.Unmarshal(m, b)
}
func (m *ServerLoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerLoginRes.Marshal(b, m, deterministic)
}
func (m *ServerLoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerLoginRes.Merge(m, src)
}
func (m *ServerLoginRes) XXX_Size() int {
	return xxx_messageInfo_ServerLoginRes.Size(m)
}
func (m *ServerLoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerLoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_ServerLoginRes proto.InternalMessageInfo

func (m *ServerLoginRes) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type AccountLoginReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Number               uint32   `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	MachineID            string   `protobuf:"bytes,4,opt,name=machineID,proto3" json:"machineID,omitempty"`
	Addr                 string   `protobuf:"bytes,5,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountLoginReq) Reset()         { *m = AccountLoginReq{} }
func (m *AccountLoginReq) String() string { return proto.CompactTextString(m) }
func (*AccountLoginReq) ProtoMessage()    {}
func (*AccountLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc2b35845d6121f3, []int{2}
}

func (m *AccountLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountLoginReq.Unmarshal(m, b)
}
func (m *AccountLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountLoginReq.Marshal(b, m, deterministic)
}
func (m *AccountLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountLoginReq.Merge(m, src)
}
func (m *AccountLoginReq) XXX_Size() int {
	return xxx_messageInfo_AccountLoginReq.Size(m)
}
func (m *AccountLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_AccountLoginReq proto.InternalMessageInfo

func (m *AccountLoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccountLoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AccountLoginReq) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *AccountLoginReq) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *AccountLoginReq) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type AccountLoginRes struct {
	Result               uint32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Number               uint32   `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Uid                  uint32   `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountLoginRes) Reset()         { *m = AccountLoginRes{} }
func (m *AccountLoginRes) String() string { return proto.CompactTextString(m) }
func (*AccountLoginRes) ProtoMessage()    {}
func (*AccountLoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc2b35845d6121f3, []int{3}
}

func (m *AccountLoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountLoginRes.Unmarshal(m, b)
}
func (m *AccountLoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountLoginRes.Marshal(b, m, deterministic)
}
func (m *AccountLoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountLoginRes.Merge(m, src)
}
func (m *AccountLoginRes) XXX_Size() int {
	return xxx_messageInfo_AccountLoginRes.Size(m)
}
func (m *AccountLoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountLoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_AccountLoginRes proto.InternalMessageInfo

func (m *AccountLoginRes) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *AccountLoginRes) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccountLoginRes) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *AccountLoginRes) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type AccountKickRes struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Number               uint32   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Force                bool     `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountKickRes) Reset()         { *m = AccountKickRes{} }
func (m *AccountKickRes) String() string { return proto.CompactTextString(m) }
func (*AccountKickRes) ProtoMessage()    {}
func (*AccountKickRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc2b35845d6121f3, []int{4}
}

func (m *AccountKickRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountKickRes.Unmarshal(m, b)
}
func (m *AccountKickRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountKickRes.Marshal(b, m, deterministic)
}
func (m *AccountKickRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountKickRes.Merge(m, src)
}
func (m *AccountKickRes) XXX_Size() int {
	return xxx_messageInfo_AccountKickRes.Size(m)
}
func (m *AccountKickRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountKickRes.DiscardUnknown(m)
}

var xxx_messageInfo_AccountKickRes proto.InternalMessageInfo

func (m *AccountKickRes) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccountKickRes) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *AccountKickRes) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type AccountJoinOtherRes struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountJoinOtherRes) Reset()         { *m = AccountJoinOtherRes{} }
func (m *AccountJoinOtherRes) String() string { return proto.CompactTextString(m) }
func (*AccountJoinOtherRes) ProtoMessage()    {}
func (*AccountJoinOtherRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc2b35845d6121f3, []int{5}
}

func (m *AccountJoinOtherRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountJoinOtherRes.Unmarshal(m, b)
}
func (m *AccountJoinOtherRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountJoinOtherRes.Marshal(b, m, deterministic)
}
func (m *AccountJoinOtherRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountJoinOtherRes.Merge(m, src)
}
func (m *AccountJoinOtherRes) XXX_Size() int {
	return xxx_messageInfo_AccountJoinOtherRes.Size(m)
}
func (m *AccountJoinOtherRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountJoinOtherRes.DiscardUnknown(m)
}

var xxx_messageInfo_AccountJoinOtherRes proto.InternalMessageInfo

func (m *AccountJoinOtherRes) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type AccountLoginFailedReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountLoginFailedReq) Reset()         { *m = AccountLoginFailedReq{} }
func (m *AccountLoginFailedReq) String() string { return proto.CompactTextString(m) }
func (*AccountLoginFailedReq) ProtoMessage()    {}
func (*AccountLoginFailedReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc2b35845d6121f3, []int{6}
}

func (m *AccountLoginFailedReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountLoginFailedReq.Unmarshal(m, b)
}
func (m *AccountLoginFailedReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountLoginFailedReq.Marshal(b, m, deterministic)
}
func (m *AccountLoginFailedReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountLoginFailedReq.Merge(m, src)
}
func (m *AccountLoginFailedReq) XXX_Size() int {
	return xxx_messageInfo_AccountLoginFailedReq.Size(m)
}
func (m *AccountLoginFailedReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountLoginFailedReq.DiscardUnknown(m)
}

var xxx_messageInfo_AccountLoginFailedReq proto.InternalMessageInfo

func (m *AccountLoginFailedReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type AccountBlockReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountBlockReq) Reset()         { *m = AccountBlockReq{} }
func (m *AccountBlockReq) String() string { return proto.CompactTextString(m) }
func (*AccountBlockReq) ProtoMessage()    {}
func (*AccountBlockReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc2b35845d6121f3, []int{7}
}

func (m *AccountBlockReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountBlockReq.Unmarshal(m, b)
}
func (m *AccountBlockReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountBlockReq.Marshal(b, m, deterministic)
}
func (m *AccountBlockReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountBlockReq.Merge(m, src)
}
func (m *AccountBlockReq) XXX_Size() int {
	return xxx_messageInfo_AccountBlockReq.Size(m)
}
func (m *AccountBlockReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountBlockReq.DiscardUnknown(m)
}

var xxx_messageInfo_AccountBlockReq proto.InternalMessageInfo

func (m *AccountBlockReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type AccountExitReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountExitReq) Reset()         { *m = AccountExitReq{} }
func (m *AccountExitReq) String() string { return proto.CompactTextString(m) }
func (*AccountExitReq) ProtoMessage()    {}
func (*AccountExitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc2b35845d6121f3, []int{8}
}

func (m *AccountExitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountExitReq.Unmarshal(m, b)
}
func (m *AccountExitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountExitReq.Marshal(b, m, deterministic)
}
func (m *AccountExitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountExitReq.Merge(m, src)
}
func (m *AccountExitReq) XXX_Size() int {
	return xxx_messageInfo_AccountExitReq.Size(m)
}
func (m *AccountExitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountExitReq.DiscardUnknown(m)
}

var xxx_messageInfo_AccountExitReq proto.InternalMessageInfo

func (m *AccountExitReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*ServerLoginReq)(nil), "model.serverLoginReq")
	proto.RegisterType((*ServerLoginRes)(nil), "model.serverLoginRes")
	proto.RegisterType((*AccountLoginReq)(nil), "model.accountLoginReq")
	proto.RegisterType((*AccountLoginRes)(nil), "model.accountLoginRes")
	proto.RegisterType((*AccountKickRes)(nil), "model.accountKickRes")
	proto.RegisterType((*AccountJoinOtherRes)(nil), "model.accountJoinOtherRes")
	proto.RegisterType((*AccountLoginFailedReq)(nil), "model.accountLoginFailedReq")
	proto.RegisterType((*AccountBlockReq)(nil), "model.accountBlockReq")
	proto.RegisterType((*AccountExitReq)(nil), "model.accountExitReq")
}

func init() { proto.RegisterFile("game_data.proto", fileDescriptor_cc2b35845d6121f3) }

var fileDescriptor_cc2b35845d6121f3 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x5d, 0x4b, 0xfb, 0x30,
	0x14, 0xc6, 0xe9, 0xb6, 0x8e, 0x35, 0xb0, 0x17, 0xfa, 0x7f, 0xa1, 0x88, 0x17, 0x23, 0x57, 0xbd,
	0x50, 0x41, 0xf6, 0x0d, 0x74, 0x8a, 0x53, 0x41, 0x08, 0x88, 0xe0, 0x8d, 0x64, 0xcd, 0x71, 0x0b,
	0xb6, 0x4d, 0x4d, 0xd3, 0x39, 0x3f, 0x87, 0xb7, 0x7e, 0x58, 0xc9, 0x69, 0xe9, 0x5c, 0x61, 0xdb,
	0xdd, 0x73, 0x9e, 0x9c, 0x9e, 0xf3, 0xfc, 0x92, 0x92, 0xe1, 0x82, 0x27, 0xf0, 0x22, 0xb8, 0xe1,
	0x67, 0x99, 0x56, 0x46, 0xf9, 0x6e, 0xa2, 0x04, 0xc4, 0xf4, 0xdb, 0x21, 0x83, 0x1c, 0xf4, 0x0a,
	0xf4, 0xbd, 0x5a, 0xc8, 0x94, 0xc1, 0xbb, 0xef, 0x93, 0x8e, 0xf9, 0xcc, 0x20, 0x70, 0xc6, 0x4e,
	0xe8, 0x32, 0xd4, 0xd6, 0xcb, 0x94, 0x36, 0x41, 0xab, 0xf4, 0xac, 0xb6, 0x5e, 0xca, 0x13, 0x08,
	0xda, 0x63, 0x27, 0xf4, 0x18, 0x6a, 0xeb, 0x45, 0x4a, 0x40, 0xd0, 0x29, 0xfb, 0xac, 0xf6, 0x47,
	0xa4, 0xbd, 0x92, 0x59, 0xe0, 0xa2, 0x65, 0xa5, 0x1f, 0x92, 0x61, 0xc2, 0xd7, 0x37, 0x4f, 0xb3,
	0xe9, 0x63, 0x0e, 0x97, 0xaa, 0x48, 0x4d, 0xd0, 0xc5, 0xd3, 0xa6, 0x4d, 0xc3, 0x46, 0xba, 0xdc,
	0xff, 0x4f, 0xba, 0x1a, 0xf2, 0x22, 0x36, 0x98, 0xaf, 0xcf, 0xaa, 0x8a, 0x7e, 0x39, 0x64, 0xc8,
	0xa3, 0xc8, 0x7e, 0x55, 0x93, 0x1c, 0x91, 0x5e, 0x91, 0x83, 0xc6, 0x94, 0x0e, 0xa6, 0xac, 0x6b,
	0x7b, 0x96, 0xf1, 0x3c, 0xff, 0x50, 0x5a, 0x20, 0x95, 0xc7, 0xea, 0xda, 0xee, 0x48, 0x8b, 0x64,
	0x0e, 0x1a, 0xd9, 0xfa, 0xac, 0xaa, 0xfc, 0x63, 0xe2, 0x25, 0x3c, 0x5a, 0xca, 0x14, 0x66, 0x53,
	0x44, 0xf4, 0xd8, 0xc6, 0xb0, 0xec, 0x5c, 0x08, 0x8d, 0xa0, 0x1e, 0x43, 0x4d, 0x55, 0x33, 0xd4,
	0x4e, 0x80, 0xad, 0xb0, 0xad, 0x46, 0xd8, 0x5d, 0x81, 0x46, 0xa4, 0x5d, 0x48, 0x81, 0x51, 0xfa,
	0xcc, 0x4a, 0xfa, 0x4c, 0x06, 0xd5, 0xc2, 0x3b, 0x19, 0xbd, 0xd9, 0x7d, 0xfb, 0x2e, 0x61, 0x33,
	0xb7, 0xb5, 0x35, 0xf7, 0x2f, 0x71, 0x5f, 0x95, 0x8e, 0xca, 0xb7, 0xed, 0xb1, 0xb2, 0xa0, 0xe7,
	0xe4, 0x4f, 0x35, 0xfb, 0x56, 0xc9, 0xf4, 0xc1, 0x2c, 0x41, 0x1f, 0x58, 0x40, 0x27, 0xe4, 0xdf,
	0x6f, 0xfe, 0x6b, 0x2e, 0x63, 0x10, 0x07, 0x9e, 0x86, 0x9e, 0xd6, 0x97, 0x76, 0x11, 0x2b, 0x0b,
	0xb1, 0xbf, 0xfd, 0xa4, 0x46, 0xbe, 0x5a, 0x4b, 0x73, 0xa0, 0x7b, 0xde, 0xc5, 0xdf, 0x7f, 0xf2,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x23, 0xfd, 0x73, 0xad, 0x11, 0x03, 0x00, 0x00,
}
