// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game2data.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerLoginMsg struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code                 int32    `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	Vip                  int32    `protobuf:"varint,5,opt,name=vip,proto3" json:"vip,omitempty"`
	MaxHWIDUseCount      int32    `protobuf:"varint,6,opt,name=maxHWIDUseCount,proto3" json:"maxHWIDUseCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerLoginMsg) Reset()         { *m = ServerLoginMsg{} }
func (m *ServerLoginMsg) String() string { return proto.CompactTextString(m) }
func (*ServerLoginMsg) ProtoMessage()    {}
func (*ServerLoginMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_30d68f4b4bf8dfb4, []int{0}
}

func (m *ServerLoginMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerLoginMsg.Unmarshal(m, b)
}
func (m *ServerLoginMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerLoginMsg.Marshal(b, m, deterministic)
}
func (m *ServerLoginMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerLoginMsg.Merge(m, src)
}
func (m *ServerLoginMsg) XXX_Size() int {
	return xxx_messageInfo_ServerLoginMsg.Size(m)
}
func (m *ServerLoginMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerLoginMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ServerLoginMsg proto.InternalMessageInfo

func (m *ServerLoginMsg) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ServerLoginMsg) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServerLoginMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerLoginMsg) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ServerLoginMsg) GetVip() int32 {
	if m != nil {
		return m.Vip
	}
	return 0
}

func (m *ServerLoginMsg) GetMaxHWIDUseCount() int32 {
	if m != nil {
		return m.MaxHWIDUseCount
	}
	return 0
}

type AccountMsg struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Number               uint32   `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	HWID                 string   `protobuf:"bytes,4,opt,name=hWID,proto3" json:"hWID,omitempty"`
	Addr                 string   `protobuf:"bytes,5,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountMsg) Reset()         { *m = AccountMsg{} }
func (m *AccountMsg) String() string { return proto.CompactTextString(m) }
func (*AccountMsg) ProtoMessage()    {}
func (*AccountMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_30d68f4b4bf8dfb4, []int{1}
}

func (m *AccountMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountMsg.Unmarshal(m, b)
}
func (m *AccountMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountMsg.Marshal(b, m, deterministic)
}
func (m *AccountMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountMsg.Merge(m, src)
}
func (m *AccountMsg) XXX_Size() int {
	return xxx_messageInfo_AccountMsg.Size(m)
}
func (m *AccountMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AccountMsg proto.InternalMessageInfo

func (m *AccountMsg) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccountMsg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AccountMsg) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *AccountMsg) GetHWID() string {
	if m != nil {
		return m.HWID
	}
	return ""
}

func (m *AccountMsg) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func init() {
	proto.RegisterType((*ServerLoginMsg)(nil), "model.serverLoginMsg")
	proto.RegisterType((*AccountMsg)(nil), "model.accountMsg")
}

func init() { proto.RegisterFile("game2data.proto", fileDescriptor_30d68f4b4bf8dfb4) }

var fileDescriptor_30d68f4b4bf8dfb4 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbd, 0x4a, 0x03, 0x41,
	0x10, 0x80, 0x59, 0x93, 0x3b, 0xbc, 0x01, 0x8d, 0x6c, 0x21, 0x8b, 0x55, 0x48, 0x75, 0x95, 0x85,
	0x3e, 0x82, 0x29, 0x0c, 0x68, 0xb3, 0x20, 0xa9, 0x37, 0xb7, 0xc3, 0x19, 0x70, 0x7f, 0x98, 0xdd,
	0x8b, 0xda, 0xfb, 0x18, 0x3e, 0xac, 0xcc, 0x44, 0x52, 0xa4, 0xfb, 0xe6, 0x9b, 0x85, 0xf9, 0x58,
	0x58, 0x8c, 0x2e, 0xe0, 0x83, 0x77, 0xd5, 0xdd, 0x67, 0x4a, 0x35, 0xe9, 0x26, 0x24, 0x8f, 0x1f,
	0xab, 0x5f, 0x05, 0xd7, 0x05, 0xe9, 0x80, 0xf4, 0x92, 0xc6, 0x7d, 0x7c, 0x2d, 0xa3, 0xd6, 0x30,
	0xaf, 0xdf, 0x19, 0x8d, 0x5a, 0xaa, 0xbe, 0xb1, 0xc2, 0xec, 0x72, 0xa2, 0x6a, 0x2e, 0x8e, 0x8e,
	0x99, 0x5d, 0x74, 0x01, 0xcd, 0x6c, 0xa9, 0xfa, 0xce, 0x0a, 0xb3, 0x1b, 0x92, 0x47, 0x33, 0x3f,
	0xbe, 0x63, 0xd6, 0x37, 0x30, 0x3b, 0xec, 0xb3, 0x69, 0x44, 0x31, 0xea, 0x1e, 0x16, 0xc1, 0x7d,
	0x3d, 0x6f, 0x37, 0xeb, 0xb7, 0x82, 0x4f, 0x69, 0x8a, 0xd5, 0xb4, 0xb2, 0x3d, 0xd7, 0xab, 0x1f,
	0x05, 0xe0, 0x86, 0x81, 0x99, 0xd3, 0xee, 0xe0, 0x72, 0x2a, 0x48, 0x72, 0x56, 0xc9, 0xd9, 0xd3,
	0xcc, 0xbb, 0xec, 0x4a, 0xf9, 0x4c, 0xe4, 0x25, 0xb3, 0xb3, 0xa7, 0x59, 0xdf, 0x42, 0x1b, 0xa7,
	0xb0, 0x43, 0x92, 0xd8, 0x2b, 0xfb, 0x3f, 0x71, 0xee, 0xfb, 0x76, 0xb3, 0x96, 0xdc, 0xce, 0x0a,
	0xb3, 0x73, 0xde, 0x93, 0xf4, 0x76, 0x56, 0x78, 0xd7, 0xca, 0x9f, 0x3d, 0xfe, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x07, 0xbc, 0xf7, 0x1d, 0x46, 0x01, 0x00, 0x00,
}
