# Generated by Django 4.2.2 on 2025-05-10 08:03

from django.db import migrations


def create_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("app1", "Profile")

    for user in User.objects.all():
        Profile.objects.get_or_create(user=user, email_verified=False)


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_profile"),
    ]

    operations = [
        migrations.RunPython(create_profiles),
    ]
