# Generated by Django 4.2.2 on 2025-08-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0006_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="item_index",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item_section",
            field=models.IntegerField(),
        ),
    ]
