name: Call Build and Deploy Server
on:
  workflow_call:
    inputs:
      server_name:
        required: true
        type: string
      tag:
        required: true
        type: string
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/${{ inputs.server_name }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.server_name }}:${{ inputs.tag }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ inputs.server_name }}:${{ inputs.tag }}
            docker stop ${{ inputs.server_name }} || true
            docker rm ${{ inputs.server_name }} || true
            ./docker/${{ inputs.server_name }}/start.sh ${{ inputs.tag }}
