name: Build and Deploy Servers
on:
  push:
    tags:
      - "v*"
jobs:
  build-server-connect:
    uses: ./.github/workflows/build-deploy.yml
    with:
      server_name: "server-connect"
      tag: ${{ github.ref_name }}
    secrets: inherit

  build-server-game:
    needs: build-server-connect
    uses: ./.github/workflows/build-deploy.yml
    with:
      server_name: "server-game"
      tag: ${{ github.ref_name }}
    secrets: inherit

  build-server-web:
    needs: build-server-game
    uses: ./.github/workflows/build-deploy.yml
    with:
      server_name: "server-web"
      tag: ${{ github.ref_name }}
    secrets: inherit
