name: Build and Deploy Servers
on:
  push:
    tags:
      - "v*"
jobs:
  build-server-connect:
    uses: ./.github/workflows/build_deploy.yml
    with:
      server_name: "server_connect"
      tag: ${{ github.ref_name }}
    secrets: inherit

  build-server-game:
    uses: ./.github/workflows/build_deploy.yml
    with:
      server_name: "server_game"
      tag: ${{ github.ref_name }}
    secrets: inherit

  build-server-web:
    uses: ./.github/workflows/build_deploy.yml
    with:
      server_name: "server_web"
      tag: ${{ github.ref_name }}
    secrets: inherit
