name: Build and Deploy Game Server
on:
  push:
    paths:
      - "src/server_game/**"
jobs:
  build-server-game:
    uses: ./.github/workflows/build_deploy.yml
    with:
      server_name: "server_game"
      tag: "latest"
