name: Build and Deploy Connect Server
on:
  push:
    paths:
      - "src/server-connect/**"
jobs:
  build-server-connect:
    uses: ./.github/workflows/build-deploy.yml
    with:
      server_name: "server-connect"
      tag: "latest"
    secrets: inherit
