name: Build and Deploy Connect Server
on:
  push:
    paths:
      - "src/server_connect/**"
jobs:
  build-server-connect:
    uses: ./.github/workflows/build_deploy.yml
    with:
      server_name: "server_connect"
      tag: "latest"
