name: Sync to GitLab
on:
  push:
    branches: ["*"]
    tags: ["*"]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/xujintao/balgass.git || \
          git remote set-url gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/xujintao/balgass.git
          git push gitlab --all
          git push gitlab --tags
